### ISSUE TITLE
[TypeError: null is not an object (evaluating 'RNFusedLocation.getCurrentPosition')]

### ISSUE THREAD

**Issue by Lain27** [Agontuk/react-native-geolocation-service#246]
i followed the setup and i keep getting [TypeError: null is not an object (evaluating 'RNFusedLocation.getCurrentPosition')] 
 
- react-native": "0.63.4"
- react-native-geolocation-service": "^5.2.0"

`Geolocation.getCurrentPosition(
            (position) => {
              console.log(position);
            },
            (error) => {
              console.log(error.code, error.message);
            },
            {enableHighAccuracy: true, timeout: 15000, maximumAge: 10000},
          );`

**Comment by Lain27** [comment]
Fixed by rebuilding the project

**Comment by ImanEmadi** [comment]
what Emulator are you using ? 
i am having exact same problem , in Nox player emulator , but rebuilding it ( plus all available solutions on internet ) did NOT fix the problem ...

**Comment by muttaqeen93** [comment]
can you help how to get rid of this issue please
